 let burger = [
   {
     id: 0,
     name: "Burger Cheese",
     price: 12.0,
     description: "mit Rindfleisch, Käse, Tomaten, Gurken, Salat",
     amount: 1,
     img: "./assets/img/burger_cheese.jpg",
   },
   {
     id: 1,
     name: "Burger Bacon",
     price: 13.0,
     description: "mit Rindfleisch, Käse, Tomaten, Gurken, Salat, Bacon",
     amount: 1,
     img: "./assets/img/burger_bacon.jpg",
   },
   {
     id: 2,
     name: "Burger Veggie",
     price: 11.0,
     description: "mit Gemüse, Käse, Tomaten, Gurken, Salat",
     amount: 1,
     img: "./assets/img/burger_veggie.jpg",
   },
   {
     id: 3,
     name: "Burger Chicken",
     price: 12.0,
     description: "mit Hähnchen, Käse, Tomaten, Gurken, Salat",
     amount: 1,
     img: "./assets/img/burger_chicken.jpg",
   },
   {
     id: 4,
     name: "Burger Fish",
     price: 13.0,
     description: "mit Fisch, Käse, Tomaten, Gurken, Salat",
     amount: 1,
     img: "./assets/img/burger_fish.jpg",
   },
 ];