 let burger = [
   {
     id: 5,
     name: "Burger Cheese",
     price: 12.0,
     description: "mit Rindfleisch, Käse, Tomaten, Gurken, Salat",
     amount: 0,
     img: "./assets/img/burger_cheese.jpg",
     icon: "./assets/img/delete.png",
   },
   {
     id: 6,
     name: "Burger Bacon",
     price: 13.0,
     description: "mit Rindfleisch, Käse, Tomaten, Gurken, Salat, Bacon",
     amount: 0,
     img: "./assets/img/burger_bacon.jpg",
     icon: "./assets/img/delete.png",
   },
   {
     id: 7,
     name: "Burger Veggie",
     price: 11.0,
     description: "mit Gemüse, Käse, Tomaten, Gurken, Salat",
     amount: 0,
     img: "./assets/img/burger_veggie.jpg",
     icon: "./assets/img/delete.png",
   },
   {
     id: 8,
     name: "Burger Chicken",
     price: 12.0,
     description: "mit Hähnchen, Käse, Tomaten, Gurken, Salat",
     amount: 0,
     img: "./assets/img/burger_chicken.jpg",
     icon: "./assets/img/delete.png",
   },
   {
     id: 9,
     name: "Burger Fish",
     price: 13.0,
     description: "mit Fisch, Käse, Tomaten, Gurken, Salat",
     amount: 0,
     img: "./assets/img/burger_fish.jpg",
     icon: "./assets/img/delete.png",
   },
 ];