let category = [
  {
    id: 1,
    selector: "pizza",
    name: "Pizza",
    img: "../assets/img/CategoryPizza-.jpg",
    bewertung: "4,2 von 5",
    items: typeof pizza !== "undefined" ? pizza : [],
  },
  {
    id: 2,
    selector: "burger",
    name: "Burger",
    img: "../assets/img/CategoryBurger.jpg",
    bewertung: "4,2 von 5",
    items: typeof burger !== "undefined" ? burger : [],
  },
  {
    id: 3,
    selector: "pasta",
    name: "Pasta",
    img: "./assets/img/pasta_aglio_e_olio.jpg",
    bewertung: "4,2 von 5",
    items: typeof pasta !== "undefined" ? pasta : [],
  },
  {
    id: 4,
    selector: "salat",
    name: "Salat",
    img: "../assets/img/CategorySalad.jpg",
    bewertung: "4,2 von 5",
    items: typeof salat !== "undefined" ? salat : [],
  },
  {
    id: 5,
    selector: "toppigs",
    name: "Toppigs",
    img: "./assets/img/tiramisu.jpg",
    bewertung: "4,2 von 5",
    items: typeof toppigs !== "undefined" ? toppigs : [],
  },
  {
    id: 6,
    selector: "drinks",
    name: "Drinks",
    img: "./assets/img/tiramisu.jpg",
    bewertung: "4,2 von 5",
    items: typeof drinks !== "undefined" ? drinks : [],
  },
];
let baskets = [];
