let drinks = [
  {
    id: 0,
    name: "Cola",
    price: 3.0,
    description: "mit Zucker, Koffein, Kohlensäure",
    amount: 1,
    img: "./assets/img/cola.jpg",
  },
  {
    id: 1,
    name: "Fanta",
    price: 3.0,
    description: "mit Zucker, Orangensaft, Kohlensäure",
    amount: 1,
    img: "./assets/img/fanta.jpg",
  },
  {
    id: 2,
    name: "Sprite",
    price: 3.0,
    description: "mit Zucker, Zitronensaft, Kohlensäure",
    amount: 1,
    img: "./assets/img/sprite.jpg",
  },
  {
    id: 3,
    name: "Apfelsaft",
    price: 3.0,
    description: "mit Zucker, Apfelsaft, Kohlensäure",
    amount: 1,
    img: "./assets/img/apfelsaft.jpg",
  },
  {
    id: 4,
    name: "Orangensaft",
    price: 3.0,
    description: "mit Zucker, Orangensaft, Kohlensäure",
    amount: 1,
    img: "./assets/img/orangensaft.jpg",
  },
];