let drinks = [
  {
    id: 25,
    name: "Cola",
    price: 3.0,
    description: "mit Zucker, Koffein, Kohlensäure",
    amount: 0,
    img: "./assets/img/cola.jpg",
    icon: "./assets/img/delete.png",
  },
  {
    id: 26,
    name: "Fanta",
    price: 3.0,
    description: "mit Zucker, Orangensaft, Kohlensäure",
    amount: 0,
    img: "./assets/img/fanta.jpg",
    icon: "./assets/img/delete.png",
  },
  {
    id: 27,
    name: "Sprite",
    price: 3.0,
    description: "mit Zucker, Zitronensaft, Kohlensäure",
    amount: 0,
    img: "./assets/img/sprite.jpg",
    icon: "./assets/img/delete.png",
  },
  {
    id: 28,
    name: "Apfelsaft",
    price: 3.0,
    description: "mit Zucker, Apfelsaft, Kohlensäure",
    amount: 0,
    img: "./assets/img/apfelsaft.jpg",
    icon: "./assets/img/delete.png",
  },
  {
    id: 29,
    name: "Orangensaft",
    price: 3.0,
    description: "mit Zucker, Orangensaft, Kohlensäure",
    amount: 0,
    img: "./assets/img/orangensaft.jpg",
    icon: "./assets/img/delete.png",
  },
];