let pasta = [
  {
    id: 0,
    name: "Pasta Carbonara",
    price: 12.0,
    description: "mit Speck, Ei, Sahnesauce",
    amount: 0,
    img: "./assets/img/pasta_carbonara.jpg",
    icon: "./assets/img/delete.png",
  },
  {
    id: 1,
    name: "Pasta Bolognese",
    price: 12.0,
    description: "mit Hackfleischsauce",
    amount: 0,
    img: "./assets/img/pasta_bolognese.jpg",
    icon: "./assets/img/delete.png",
  },
  {
    id: 2,
    name: "Pasta Aglio e Olio",
    price: 11.0,
    description: "mit Knoblauch, Olivenöl, Peperoni",
    amount: 0,
    img: "./assets/img/pasta_aglio_e_olio.jpg",
    icon: "./assets/img/delete.png",
  },
  {
    id: 3,
    name: "Pasta Arrabiata",
    price: 11.0,
    description: "mit Tomatensauce, Peperoni",
    amount: 0,
    img: "./assets/img/pasta_arrabiata.jpg",
    icon: "./assets/img/delete.png",
  },
  {
    id: 4,
    name: "Pasta Pesto",
    price: 11.0,
    description: "mit Basilikum, Pinienkernen, Parmesan",
    amount: 0,
    img: "./assets/img/pasta_pesto.jpg",
    icon: "./assets/img/delete.png",
  },
];