
let pizza = [
  {
    id: 0,
    name: "Pizza Margherita",
    price: 15.0,
    description: "mit Tomaten, Mozzarella, Basilikum",
    amount: 0,
    img: "./assets/img/pizza_margherita.jpg",
    icon: "./assets/img/delete.png",
  },
  {
    id: 1,
    name: "Pizza Salami",
    price: 16.0,
    description: "mit Tomaten, Mozzarella, Salami",
    amount: 0,
    img: "./assets/img/pizza_salami.jpg",
    icon: "./assets/img/delete.png",
  },
  {
    id: 2,
    name: "Pizza Funghi",
    price: 16.0,
    description: "mit Tomaten, Mozzarella, Champignons",
    amount: 0,
    img: "./assets/img/pizza_funghi.jpg",
    icon: "./assets/img/delete.png",
  },
  {
    id: 3,
    name: "Pizza Prosciutto",
    price: 16.0,
    description: "mit Tomaten, Mozzarella, Schinken",
    amount: 0,
    img: "./assets/img/pizza_prosciutto.jpg",
    icon: "./assets/img/delete.png",
  },
  {
    id: 4,
    name: "Pizza Stagioni",
    price: 17.0,
    description: "mit Tomaten, Mozzarella, Schinken, Champignons, Oliven",
    amount: 0,
    img: "./assets/img/pizza_quattro_stagioni.jpg",
    icon: "./assets/img/delete.png",
  },
];