let salat = [
  {
    id: 0,
    name: "Salat Caprese",
    price: 9.0,
    description: "mit Tomaten, Mozzarella, Basilikum",
    amount: 1,
    img: "./assets/img/salat_caprese.jpg",
  },
  {
    id: 1,
    name: "Salat Caesar",
    price: 10.0,
    description: "mit Hähnchen, Parmesan, Croutons",
    amount: 1,
    img: "./assets/img/salat_caesar.jpg",
  },
  {
    id: 2,
    name: "Salat Nicoise",
    price: 10.0,
    description: "mit Thunfisch, Oliven, Ei, Bohnen",
    amount: 1,
    img: "./assets/img/salat_nicoise.jpg",
  },
  {
    id: 3,
    name: "Salat Waldorf",
    price: 9.0,
    description: "mit Äpfeln, Walnüssen, Sellerie",
    amount: 1,
    img: "./assets/img/salat_waldorf.jpg",
  },
  {
    id: 4,
    name: "Salat Griechisch",
    price: 9.0,
    description: "mit Oliven, Feta, Gurken, Tomaten",
    amount: 1,
    img: "./assets/img/salat_griechisch.jpg",
  },
];