let salat = [
  {
    id: 15,
    name: "Salat Caprese",
    price: 9.0,
    description: "mit Tomaten, Mozzarella, Basilikum",
    amount: 0,
    img: "./assets/img/salat_caprese.jpg",
    icon: "./assets/img/delete.png",
  },
  {
    id: 16,
    name: "Salat Caesar",
    price: 10.0,
    description: "mit Hähnchen, Parmesan, Croutons",
    amount: 0,
    img: "./assets/img/salat_caesar.jpg",
    icon: "./assets/img/delete.png",
  },
  {
    id: 17,
    name: "Salat Nicoise",
    price: 10.0,
    description: "mit Thunfisch, Oliven, Ei, Bohnen",
    amount: 0,
    img: "./assets/img/salat_nicoise.jpg",
    icon: "./assets/img/delete.png",
  },
  {
    id: 18,
    name: "Salat Waldorf",
    price: 9.0,
    description: "mit Äpfeln, Walnüssen, Sellerie",
    amount: 0,
    img: "./assets/img/salat_waldorf.jpg",
    icon: "./assets/img/delete.png",
  },
  {
    id: 19,
    name: "Salat Griechisch",
    price: 9.0,
    description: "mit Oliven, Feta, Gurken, Tomaten",
    amount: 0,
    img: "./assets/img/salat_griechisch.jpg",
    icon: "./assets/img/delete.png",
  },
];