let toppigs = [
  {
    id: 20,
    name: "Tiramisu",
    price: 5.0,
    description: "mit Mascarpone, Kaffee, Löffelbiskuits",
    amount: 0,
    img: "./assets/img/tiramisu.jpg",
    icon: "./assets/img/delete.png",
  },
  {
    id: 21,
    name: "Panna Cotta",
    price: 5.0,
    description: "mit Sahne, Vanille, Erdbeersauce",
    amount: 0,
    img: "./assets/img/panna_cotta.jpg",
    icon: "./assets/img/delete.png",
  },
  {
    id: 22,
    name: "Tarte Tatin",
    price: 5.0,
    description: "mit Äpfeln, Blätterteig, Vanilleeis",
    amount: 0,
    img: "./assets/img/tarte_tatin.jpg",
    icon: "./assets/img/delete.png",
  },
  {
    id: 23,
    name: "Crème Brûlée",
    price: 5.0,
    description: "mit Eigelb, Zucker, Vanille",
    amount: 0,
    img: "./assets/img/creme_brulee.jpg",
    icon: "./assets/img/delete.png",
  },
  {
    id: 24,
    name: "Mousse au Chocolat",
    price: 5.0,
    description: "mit Schokolade, Eigelb, Sahne",
    amount: 0,
    img: "./assets/img/mousse_au_chocolat.jpg",
    icon: "./assets/img/delete.png",
  },
];