
let Pizza = [
  {
    id: 0,
    category: "Pizza",
    name: "Pizza Margherita",
    price: 15.0,
    description: "mit Tomaten, Mozzarella, Basilikum",
    amount: 1,
    img: "./assets/img/pizza_margherita.jpg",
    totalsPric: "",
  },
  {
    id: 1,
    category: "Pizza",
    name: "Pizza Salami",
    price: 16.0,
    description: "mit Tomaten, Mozzarella, Salami",
    amount: 1,
    img: "./assets/img/pizza_salami.jpg",
  },
  {
    id: 2,
    category: "Pizza",
    name: "Pizza Funghi",
    price: 16.0,
    description: "mit Tomaten, Mozzarella, Champignons",
    amount: 1,
    img: "./assets/img/pizza_funghi.jpg",
  },
  {
    id: 3,
    category: "Pizza",
    name: "Pizza Prosciutto",
    price: 16.0,
    description: "mit Tomaten, Mozzarella, Schinken",
    amount: 0,
    img: "./assets/img/pizza_prosciutto.jpg",
  },
  {
    id: 4,
    category: "Pizza",
    name: "Pizza Stagioni",
    price: 17.0,
    description: "mit Tomaten, Mozzarella, Schinken, Champignons, Oliven",
    amount: 0,
    img: "./assets/img/pizza_quattro_stagioni.jpg",
  },
]